### ISSUE TITLE
推荐一个南科大电子版作业模板，

### ISSUE THREAD

**Issue by zhuhu00** [SUSTC/latex-template#1]
github地址为：https://github.com/zhuhu00/SUSTech_hw_template

**Comment by liziwl** [comment]
感谢贡献。顺便发现 README 中的一个拼写错误是 `XeLaTex`，不是 `xlatex`，并建议编译一份 pdf 放入其中或者插入编译后的截图。

**Comment by zhuhu00** [comment]
已修改，且加上了一个效果图

感谢指出错误。
